sudo: false

env:
  - STACK_YAML=stack.yaml
  - STACK_YAML=stack-7.10.yaml

addons:
  apt:
    packages:
      - libgmp-dev
      - python3-dbus python3-gi

install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version
  # python reqs
  - pip install -r test/Mock/requirements.txt

script:
  - stack setup --no-terminal
  - stack build --ghc-options=-Werror --no-terminal --flag ble:-hasBluez --flag ble:hasDBus
  - stack test --ghc-options=-Werror --no-terminal  --flag ble:-hasBluez --flag ble:hasDBus
  - cmp README.md examples/README.lhs

cache:
  directories:
    - $HOME/.stack
    - $HOME/.pip
