sudo: required
dist: trusty

python: "3.4"

env:
  global:
    - BLE_TEST_LOG_FILE=test.log
  matrix:
    - STACK_YAML=stack.yaml BLE_TEST_LOG_FILE=test.log
    - STACK_YAML=stack-7.10.yaml BLE_TEST_LOG_FILE=test.log

addons:
  apt:
    packages:
      - libgmp-dev libdbus-1-dev libdbus-glib-1-dev
      - python3-dbus python3-gi python3-pip

install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version
  # python reqs
  - pip3 install --user -r test/Mock/requirements.txt

script:
  - stack setup --no-terminal
  - stack build --ghc-options=-Werror --no-terminal --flag ble:-hasBluez --flag ble:hasDBus
  - touch test.log
  - stack test --ghc-options=-Werror --no-terminal  --flag ble:-hasBluez --flag ble:hasDBus || cat "$BLE_TEST_LOG_FILE" && exit 1
  - cmp README.md examples/README.lhs

cache:
  directories:
    - $HOME/.stack
    - $HOME/.pip
