name:                ble
version:             0.3.2.1
synopsis:            Bluetooth Low Energy (BLE) peripherals
description:         >
    This package provides a Haskell API for writing Bluetooth Low Energy
    peripherals.

homepage:            http://github.com/plow-technologies/ble#readme
license:             BSD3
license-file:        LICENSE
author:              Julian K. Arni
maintainer:          jkarni@turingjump.com
copyright:           2016 Julian K. Arni
github:              plow-technologies/ble
stability:           alpha
tested-with:         GHC == 7.10.3, GHC == 8.0.1

ghc-options: -Wall

flags:
  bluez543:
    description: Bluez version 5.43 or greater
    manual: True
    default: False
  hasBluez:
    description: Whether to run tests that require Bluez
    manual: True
    default: True

extra-source-files:
  - README.md
  - package.yaml
  - LICENSE

when:
  - condition: flag(bluez543)
    cpp-options: -DBluezGEQ543

when:
  - condition: flag(hasBluez)
    cpp-options: -DBluez

dependencies:
  - base >= 4.8 && < 4.10
  - bytestring >= 0.10 && < 0.11
  - text >= 1 && < 2
  - d-bus >= 0.1.5 && < 0.2
  - uuid >= 1 && < 2
  - mtl >= 2.2 && < 2.3
  - transformers >= 0.4 && < 0.6
  - containers >= 0.5 && < 0.6
  - random >= 1 && < 2
  - microlens >= 0.4 && < 0.5
  - microlens-th >= 0.4 && < 0.5
  - microlens-ghc >= 0.4 && < 0.5
  - cereal >= 0.4 && < 0.6
  - data-default-class >= 0.0 && < 0.2

default-extensions:
  - AutoDeriveTypeable
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

library:
  source-dirs:      src
  other-modules:    []

tests:
  spec:
    main:            Main.hs
    source-dirs:     test
    dependencies:
      - ble
      - hspec > 2 && < 3
      - QuickCheck >= 2.8 && < 2.9
      - quickcheck-instances >= 0.3 && < 0.4
      - hslogger
#   doctest:
#     main:            Doctest.hs
#     source-dirs:     test
#     dependencies:
#       - doctest >= 0.9 && < 0.12
#       - Glob >= 0.7 && < 0.8
#       - yaml == 0.8.*

executables:
  counter:
    main:            Counter.hs
    source-dirs:     examples
    dependencies:
      - ble
      - stm
  hrs:
    main:            HeartRate.hs
    source-dirs:     examples
    dependencies:
      - ble
      - hslogger
  auth:
    main:            Auth.hs
    source-dirs:     examples
    dependencies:
      - ble
